"""baseline schema

Revision ID: 6e756620f1c6
Revises: 
Create Date: 2026-07-13 15:49:16.607077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e756620f1c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('payload_schema_version', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emitting_service', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('causation_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('previous_chain_hash', sa.String(), nullable=True),
    sa.Column('chain_hash', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('replay_relevance', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('legal_hold_id', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_ref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_ingested_at'), 'audit_events', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('emergency_safety_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoker', sa.String(), nullable=False),
    sa.Column('approver', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'RESTRICTED', name='risklevel'), nullable=False),
    sa.Column('restricted_sub_class', sa.Enum('ACADEMIC_INTEGRITY', 'ADVICE_INSUFFICIENT_CONTEXT', 'SOURCE_PROHIBITED', 'CONTROL_BYPASS', name='restrictedsubclass'), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('reviewer_role', sa.String(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'ESCALATED', 'REFUSED', name='escalationstatus'), nullable=True),
    sa.Column('route_reason', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('reviewer_decision', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trigger_condition', sa.String(), nullable=False),
    sa.Column('reviewer_role', sa.String(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('notification_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_datasets_id'), 'evaluation_datasets', ['id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('threshold_set_id', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metrics_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_id'), 'evaluation_runs', ['id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_idempotency_tenant_key')
    )
    op.create_index(op.f('ix_idempotency_records_tenant_id'), 'idempotency_records', ['tenant_id'], unique=False)
    op.create_table('model_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refusal_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('risk_scope', sa.String(), nullable=True),
    sa.Column('restricted_sub_class', sa.Enum('ACADEMIC_INTEGRITY', 'ADVICE_INSUFFICIENT_CONTEXT', 'SOURCE_PROHIBITED', 'CONTROL_BYPASS', name='restrictedsubclass'), nullable=True),
    sa.Column('mode_scope', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('safe_alternative', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restricted_topic_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restricted_sub_class', sa.Enum('ACADEMIC_INTEGRITY', 'ADVICE_INSUFFICIENT_CONTEXT', 'SOURCE_PROHIBITED', 'CONTROL_BYPASS', name='restrictedsubclass'), nullable=False),
    sa.Column('allowed_safe_alternative', sa.Text(), nullable=False),
    sa.Column('refusal_template_id', sa.String(), nullable=False),
    sa.Column('clarification_permitted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restricted_sub_class')
    )
    op.create_table('review_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('confidence_state', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('assigned_queue', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('classifier_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cases_correlation_id'), 'review_cases', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_review_cases_query_id'), 'review_cases', ['query_id'], unique=False)
    op.create_index(op.f('ix_review_cases_tenant_id'), 'review_cases', ['tenant_id'], unique=False)
    op.create_table('risk_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('rollback_target', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('permissions_summary', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rollback_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_version', sa.String(), nullable=False),
    sa.Column('to_version', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approver', sa.String(), nullable=False),
    sa.Column('impact_scan_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('payload_schema_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('authority_role', sa.String(), nullable=False),
    sa.Column('original_route', sa.String(), nullable=False),
    sa.Column('new_route', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('post_action_review_due', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_class', sa.String(), nullable=False),
    sa.Column('jurisdiction_scope', sa.String(), nullable=False),
    sa.Column('framework_scope', sa.String(), nullable=False),
    sa.Column('licence_state', sa.String(), nullable=False),
    sa.Column('authority_level', sa.String(), nullable=False),
    sa.Column('is_tenant_private', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_tenant_id'), 'sources', ['tenant_id'], unique=False)
    op.create_table('syllabus_pathways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('learning_outcome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('dataset_version_id', sa.String(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('zero_tolerance_metrics', sa.JSON(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('approver', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threshold_sets_id'), 'threshold_sets', ['id'], unique=False)
    op.create_table('topic_map_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('prerequisites', sa.String(), nullable=False),
    sa.Column('standards_summary', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('gold_answer', sa.String(), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=True),
    sa.Column('risk_scope', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_cases_id'), 'benchmark_cases', ['id'], unique=False)
    op.create_table('result_packs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('exact_config_hash', sa.String(), nullable=False),
    sa.Column('contamination_scan_status', sa.String(), nullable=True),
    sa.Column('zero_tolerance_passed', sa.Boolean(), nullable=True),
    sa.Column('promotion_eligible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_packs_id'), 'result_packs', ['id'], unique=False)
    op.create_table('security_incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('containment_status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('restricted_sub_class', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('compensating_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('corrects_event_id', sa.String(), nullable=False),
    sa.Column('correction_type', sa.String(), nullable=False),
    sa.Column('is_material', sa.Boolean(), nullable=False),
    sa.Column('correction_reason', sa.String(), nullable=False),
    sa.Column('corrected_fields_summary', sa.JSON(), nullable=False),
    sa.Column('issued_by', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('effective_for_replay', sa.Boolean(), nullable=False),
    sa.Column('payload_schema_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['corrects_event_id'], ['audit_events.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpd_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_authorizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('result_pack_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('residual_risk_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_pack_id'], ['result_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_authorizations_id'), 'promotion_authorizations', ['id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('display_restriction', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_versions_tenant_id'), 'source_versions', ['tenant_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('saved_answer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['saved_answer_id'], ['saved_answers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drafts')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_source_versions_tenant_id'), table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_table('saved_answers')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_promotion_authorizations_id'), table_name='promotion_authorizations')
    op.drop_table('promotion_authorizations')
    op.drop_table('cpd_entries')
    op.drop_table('compensating_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('security_incidents')
    op.drop_index(op.f('ix_result_packs_id'), table_name='result_packs')
    op.drop_table('result_packs')
    op.drop_index(op.f('ix_benchmark_cases_id'), table_name='benchmark_cases')
    op.drop_table('benchmark_cases')
    op.drop_table('topic_map_nodes')
    op.drop_index(op.f('ix_threshold_sets_id'), table_name='threshold_sets')
    op.drop_table('threshold_sets')
    op.drop_table('tenants')
    op.drop_table('syllabus_pathways')
    op.drop_index(op.f('ix_sources_tenant_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('safety_overrides')
    op.drop_table('safety_events')
    op.drop_table('rollback_records')
    op.drop_table('roles')
    op.drop_table('risk_policies')
    op.drop_index(op.f('ix_review_cases_tenant_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_query_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_correlation_id'), table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_table('restricted_topic_rules')
    op.drop_table('refusal_templates')
    op.drop_table('model_definitions')
    op.drop_index(op.f('ix_idempotency_records_tenant_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_evaluation_runs_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_evaluation_datasets_id'), table_name='evaluation_datasets')
    op.drop_table('evaluation_datasets')
    op.drop_table('escalation_rules')
    op.drop_table('escalation_cases')
    op.drop_table('emergency_safety_blocks')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_ingested_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
