"use client";

import { FormEvent, Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Loader2, ShieldCheck, ShieldAlert, ShieldQuestion, History } from "lucide-react";
import { PageShell } from "@/components/governance/PageShell";
import { Pill } from "@/components/governance/Pill";
import { PanelHeader, PANEL_CLASS, type PanelTone } from "@/components/governance/PanelHeader";
import { getAuthToken, getReplayManifest, ApiError, type ReplayManifest } from "@/lib/api";

const TRUST_PANEL_TONE: Record<string, PanelTone> = {
  AUTHORITATIVE: "ok",
  LIMITED: "warn",
  INCONCLUSIVE: "bad",
};

const TRUST_TONE: Record<string, "ok" | "warn" | "bad"> = {
  AUTHORITATIVE: "ok",
  LIMITED: "warn",
  INCONCLUSIVE: "bad",
};

const TRUST_ICON: Record<string, typeof ShieldCheck> = {
  AUTHORITATIVE: ShieldCheck,
  LIMITED: ShieldAlert,
  INCONCLUSIVE: ShieldQuestion,
};

function AuditReplayContent() {
  const searchParams = useSearchParams();
  const initialId = searchParams.get("correlation_id") ?? "";

  const [correlationId, setCorrelationId] = useState(initialId);
  const [manifest, setManifest] = useState<ReplayManifest | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function loadManifest(id: string) {
    if (!id.trim()) return;
    setLoading(true);
    setError("");
    try {
      const result = await getReplayManifest(getAuthToken(), id.trim());
      setManifest(result);
    } catch (err) {
      setManifest(null);
      setError(err instanceof ApiError ? err.message : "Could not build a replay manifest.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    if (initialId) loadManifest(initialId);
  }, [initialId]);

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    loadManifest(correlationId);
  }

  const TrustIcon = manifest ? TRUST_ICON[manifest.manifest_trustworthiness] ?? ShieldQuestion : ShieldQuestion;

  return (
    <PageShell
      title="Audit Replay"
      subtitle="Reconstruct the source bundle, prompt/model version, risk decision, and reviewer trail for any query, source, or prompt ID — with an honest completeness verdict."
      showMetrics={false}
    >
      <div className={PANEL_CLASS}>
        <PanelHeader icon={History} title="Build a replay manifest" />
        <form onSubmit={handleSubmit} className="flex flex-wrap gap-3">
          <input
            value={correlationId}
            onChange={(e) => setCorrelationId(e.target.value)}
            placeholder="query_id, source_id, or prompt_id (e.g. qry-4181007f4773)"
            className="flex-1 min-w-[280px] rounded-lg border border-line bg-soft px-3 py-2 text-sm text-ink outline-none focus:border-brand"
          />
          <button
            type="submit"
            disabled={loading}
            className="rounded-lg bg-brand text-white text-sm font-semibold px-4 py-2 hover:bg-brand-2 disabled:opacity-60"
          >
            {loading ? "Building…" : "Replay"}
          </button>
        </form>
        {error && <p className="text-xs text-bad mt-3">{error}</p>}
      </div>

      {loading && (
        <div className="flex items-center justify-center py-12 text-muted">
          <Loader2 className="animate-spin mr-2" size={16} /> Building replay manifest…
        </div>
      )}

      {!loading && manifest && (
        <div className="mt-6 space-y-6">
          <div className={PANEL_CLASS}>
            <PanelHeader
              icon={TrustIcon}
              tone={TRUST_PANEL_TONE[manifest.manifest_trustworthiness] ?? "brand"}
              title={`Manifest for ${manifest.correlation_id}`}
              action={
                <div className="flex items-center gap-2">
                  <Pill tone={TRUST_TONE[manifest.manifest_trustworthiness] ?? "neutral"}>
                    <TrustIcon size={12} className="mr-1 inline" />
                    {manifest.manifest_trustworthiness}
                  </Pill>
                  <Pill tone={manifest.chain_verification_result === "PASS" ? "ok" : "neutral"}>
                    Chain: {manifest.chain_verification_result}
                  </Pill>
                </div>
              }
            />
            <div className="flex flex-wrap gap-2 mb-4">
              <Pill>Status: {manifest.completeness_status}</Pill>
              <Pill>Generated by: {manifest.generated_by}</Pill>
              <Pill>{new Date(manifest.generated_at).toLocaleString()}</Pill>
            </div>

            {manifest.known_gaps.length > 0 && (
              <div className="rounded-xl border border-warn/30 bg-warn/10 p-3 mb-4 space-y-2">
                <div className="text-xs font-bold text-warn uppercase tracking-wider">
                  Known gaps — do not treat this manifest as complete
                </div>
                {manifest.known_gaps.map((gap, i) => (
                  <div key={i} className="text-xs text-ink">
                    <span className="font-semibold">{gap.event_class}</span>: expected{" "}
                    <span className="font-mono">{gap.expected_event_name}</span> — {gap.gap_reason}{" "}
                    <span className="text-muted">({gap.impact_on_replay})</span>
                  </div>
                ))}
              </div>
            )}

            {manifest.events.length === 0 ? (
              <p className="text-sm text-muted py-4">No events found for this identifier.</p>
            ) : (
              <div className="space-y-0">
                {manifest.events.map((event) => (
                  <div
                    key={event.event_id}
                    className="grid grid-cols-[160px_1fr_auto] gap-3 border-t border-line first:border-t-0 py-2.5 text-sm items-start"
                  >
                    <span className="text-xs text-muted">
                      {event.event_time ? new Date(event.event_time).toLocaleString() : "—"}
                    </span>
                    <div>
                      <span className="font-semibold text-ink">{event.event_name}</span>
                      <span className="text-xs text-muted"> · {event.emitting_service}</span>
                      <pre className="mt-1 rounded-lg border border-line bg-soft p-2 text-[11px] text-ink overflow-x-auto">
                        {JSON.stringify(event.payload, null, 2)}
                      </pre>
                    </div>
                    <Pill tone={event.chain_hash ? "ok" : "neutral"}>
                      {event.chain_hash ? "chain-verified" : "unverified"}
                    </Pill>
                  </div>
                ))}
              </div>
            )}

            <div className="mt-4 text-[11px] text-muted font-mono break-all">
              manifest_hash: {manifest.manifest_hash}
            </div>
          </div>
        </div>
      )}
    </PageShell>
  );
}

export default function AuditReplayPage() {
  return (
    <Suspense fallback={null}>
      <AuditReplayContent />
    </Suspense>
  );
}
